[package]
name = "qrs"
version = "0.1.0"
authors = ["Wang Ruochen <wangkevin920@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qrcode = { version = "0.12", default-features = false }
